Repository Raksha1906/HacktoberFest2020, pull requests merged in 2020-10, with the labels that each got.

#2 Create shaunak_vyas_intro.txt
  shaunak_vyas_intro.txt
Labels: Hacktoberfest, good first issue

#4 Create lalit_tilwani_intro.txt
  lalit_tilwani_intro.txt
Labels: Hacktoberfest, good first issue

#5 Update README.md
  README.md
Labels: Hacktoberfest

#3 Added Hello World file in Golang
  helloworld.go
Labels: Hacktoberfest, good first issue

#7 Add Intro
  rupinderjeet_intro.txt
Labels: Hacktoberfest, good first issue

#6 Create vaishnavi_jha_intro.txt
  vaishnavi_jha_intro.txt
Labels: Hacktoberfest, good first issue

#9 Introduction Template
  Intro/Sample_Introduction.md
Labels: Hacktoberfest, documentation

#10 Sample code added
  Codes/Kadane's_Algorithm.c
Labels: Hacktoberfest, documentation

#8 improved text in README.md
  README.md
Labels: Hacktoberfest, good first issue

#15 :rocket:Added my intro and code file under codes & intro folder
  Codes/helloworld.html
  Intro/shubham-intro.txt
Labels: Hacktoberfest

#14 hello world in html
  Codes/Bk_html.html
Labels: Hacktoberfest

#13 hello world in c#
  Codes/Bk_c#.cs
Labels: Hacktoberfest

#12 hello world in react
  Codes/Bk_React.js
Labels: Hacktoberfest

#11 hello world in javascript
  Codes/Bk_javascript.js
Labels: Hacktoberfest

#19 My Intro
  Intro/Intro.txt
Labels: Hacktoberfest, good first issue

#20 Added my introduction
  Intro/Yashmita_intro.txt
Labels: Hacktoberfest, good first issue

#26 Patch 1
  Projects/Survey Form/index.html
  Projects/Survey Form/style.css
Labels: Hacktoberfest

#28 Added a C program
  Codes/adding_2_polynomials_using_LL.c
Labels: Hacktoberfest

#23 Added my program in the Codes Folder
  Codes/helloworld.go
Labels: Hacktoberfest

#31 WebPage_Shahina
  Projects/Webpage-Shahina/Intro.txt
  Projects/Webpage-Shahina/index.html
  Projects/Webpage-Shahina/styling.css
  Projects/Webpage-Shahina/v2.mp4
Labels: Hacktoberfest

#32 Boston_Number.cpp
  Codes/Boston_Number.cpp
Labels: Hacktoberfest

#34 Update helloworld.html
  Codes/helloworld.html
Labels: Hacktoberfest, documentation, good first issue

#35 Add Hello world in brainfuck
  helloworld.bf
Labels: Hacktoberfest

#36 Added my intro
  Intro/Akshat_intro.txt
Labels: Hacktoberfest, good first issue

#39 pi-rate14_add_2_nums_using_ptrs.c
  Codes/add_2_nums_using_ptrs.c
Labels: Hacktoberfest, good first issue

#40 Create apoorva_intro.txt
  Intro/apoorva_intro.txt
Labels: Hacktoberfest, good first issue

#43 Added CLI Quotes Project
  Projects/random-quotes/.gitignore
  Projects/random-quotes/LICENSE.md
  Projects/random-quotes/README.md
  Projects/random-quotes/bin/random-quotes
  Projects/random-quotes/package-lock.json
  Projects/random-quotes/package.json
  Projects/random-quotes/src/cli.js
Labels: Hacktoberfest

#41 Added my Hello World
  Codes/GS_helloworld.html
Labels: Hacktoberfest

#55 Add Code using Kotlin and add intro in new branch
  Codes/hellokotlin.kt
  Intro/pahlevikun_intro.txt
Labels: Hacktoberfest

#56 Chat_system_for_multi-thread user "form other than main branch"
  Codes/Chat_system_in_cpp/TCP_client
  Codes/Chat_system_in_cpp/TCP_client.c
  Codes/Chat_system_in_cpp/server_file/a.out
  Codes/Chat_system_in_cpp/server_file/server
  Codes/Chat_system_in_cpp/server_file/server.c
Labels: Hacktoberfest

#59 My introduction
  Intro/priyanshu_intro.txt
Labels: Hacktoberfest, good first issue

#67 Intro
  Intro/Shweta Laha_intro.txt
Labels: Hacktoberfest, good first issue

#65 Introduction added
  Intro/Shweta Laha_intro.txt
Labels: main-branch PR

#66 adding Dreamy's intro
  Intro/Sample_Introduction.md
Labels: Hacktoberfest, good first issue

#68 Quick Sort
  Codes/QuickSort.cpp
Labels: Hacktoberfest

#69 added javascript array methods codes
  Codes/js-array-methods.js
Labels: Hacktoberfest

#70 modified the folder intro
  Intro/amruta-intro.txt
Labels: Hacktoberfest, good first issue

#72 hello world alert html
  Codes/helloworldAlert.html
  Intro/eva-intro.txt
Labels: Hacktoberfest, good first issue

#75 Himanshu_Kumawat_intro added
  Intro/Himanshu_Kumawat_intro.txt
Labels: Hacktoberfest, good first issue

#76 added a ember todo app
  .DS_Store
  Projects/.DS_Store
  Projects/Ember todo/.editorconfig
  Projects/Ember todo/.ember-cli
  Projects/Ember todo/.eslintignore
  Projects/Ember todo/.eslintrc.js
  Projects/Ember todo/.gitignore
  Projects/Ember todo/.template-lintrc.js
  Projects/Ember todo/.travis.yml
  Projects/Ember todo/.watchmanconfig
  Projects/Ember todo/README.md
  Projects/Ember todo/app/app.js
  Projects/Ember todo/app/components/.gitkeep
  Projects/Ember todo/app/components/general-component.hbs
  Projects/Ember todo/app/components/general-component.js
  Projects/Ember todo/app/components/general-component/item.hbs
  Projects/Ember todo/app/components/general-component/item.js
  Projects/Ember todo/app/components/navbar.hbs
  Projects/Ember todo/app/controllers/.gitkeep
  Projects/Ember todo/app/helpers/.gitkeep
  Projects/Ember todo/app/index.html
  Projects/Ember todo/app/models/.gitkeep
  Projects/Ember todo/app/router.js
  Projects/Ember todo/app/routes/.gitkeep
  Projects/Ember todo/app/services/list.js
  Projects/Ember todo/app/styles/app.css
  Projects/Ember todo/app/templates/application.hbs
  Projects/Ember todo/app/templates/index.hbs
  Projects/Ember todo/config/environment.js
  Projects/Ember todo/config/optional-features.json
  Projects/Ember todo/config/targets.js
  Projects/Ember todo/ember-cli-build.js
  Projects/Ember todo/jsconfig.json
  Projects/Ember todo/package-lock.json
  Projects/Ember todo/package.json
  Projects/Ember todo/public/robots.txt
  Projects/Ember todo/testem.js
  Projects/Ember todo/tests/helpers/.gitkeep
  Projects/Ember todo/tests/index.html
  Projects/Ember todo/tests/integration/.gitkeep
  Projects/Ember todo/tests/integration/components/general-component-test.js
  Projects/Ember todo/tests/integration/components/general-component/item-test.js
  Projects/Ember todo/tests/integration/components/navbar-test.js
  Projects/Ember todo/tests/test-helper.js
  Projects/Ember todo/tests/unit/.gitkeep
  Projects/Ember todo/tests/unit/services/list-test.js
  Projects/Ember todo/vendor/.gitkeep
Labels: Hacktoberfest
